package com.darkSProject.ticketBooking.common.exception;

import lombok.Getter;

@Getter
public enum ErrorCode {

    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    TRAIN_NOT_EXIST,
    TRAIN_EXISTS,
    SEATS_UNAVAILABLE,
    INVALID_ROUTE,
    USER_NOT_AUTHENTICATED,
    TICKET_NOT_FOUND,
    TICKET_ALREADY_CANCELLED,
    STATION_DOES_NOT_EXIST,
    UNSUPPORTED_PAYMENT_METHOD,
    PAYMENT_FAILED,
    PAYMENT_GATEWAY_ERROR


}
